### ISSUE TITLE
Nix Steering Committee Election 2024

### ISSUE THREAD

**Issue by infinisil** [NixOS/SC-election-2024#1]
As a first step towards a better governance for official Nix projects, we are happy to announce the kick-off of the [first Nix Steering Committee election](https://github.com/NixOS/SC-election-2024)!

The Steering Committee will be the primary community leadership body, responsible for steering the official Nix projects -- organisationally, socially, and technically. This includes making decisions over what is official, managing teams, approving NixOS Foundation policies relevant for the community, being the final escalation point, and more as [detailed in the Nix Governance Constitution](https://github.com/NixOS/nix-constitutional-assembly/blob/main/constitution.md#steering-committee).

While the Steering Committee is given the authority to make decisions within the scope of its responsibilities directly, it is expected to delegate as much as possible.

Note that you can also read and publicly discuss this announcement [on Discourse](https://discourse.nixos.org/t/nix-steering-committee-election-2024/52232).

## Participating

If you're pinged by the mention of @NixOS/voters-2024 here, it means you're [automatically eligible](https://github.com/NixOS/SC-election-2024?tab=readme-ov-file#automatically-eligible-voters) to vote.

If you didn't also receive an announcement email, make sure to [check and optionally update your email address](https://github.com/NixOS/SC-election-2024/tree/main/doc/email.md).

Members of the GitHub team can:

- [Nominate](https://github.com/NixOS/SC-election-2024/tree/main/doc/nominate.md) themselves or others.
- Endorse [unconfirmed nominees](https://github.com/NixOS/SC-election-2024/pulls?q=is%3Apr+label%3Anomination+is%3Aopen) that they'd like to be able to vote for.
- [Ask questions](https://github.com/NixOS/SC-election-2024/tree/main/doc/qna.md) to nominees as the primary way of engaging with them.

If you have any questions or need support, please get in touch with the [Election Committee](https://github.com/nixos/SC-election-2024?tab=readme-ov-file#election-committee-ec).

## Timeline

- 2024-09-29 Sun: Deadline for nominations
- 2024-10-01 Tue: Deadline for endorsements
- 2024-10-03 Thu: Deadline for candidate questions
- 2024-10-06 Sun: Deadline for candidate answers, submitting voter exceptions and updating voter email addresses
- 2024-10-07 Mon: Voting starts
- 2024-10-20 Sun: Voting ends
- 2024-10-23 Wed: Results announced

The results are expected to be announced just before [NixCon 2024](https://2024.nixcon.org/) in Berlin, which starts on 2024-10-25.

**Comment by infinisil** [comment]
Since the team notification apparently didn't work, let's try it again with another @NixOS/voters-2024 mention, maybe GitHub wasn't ready the first time.

Also specifically:
- Everybody whose Email failed to be sent: @devhell @MP2E @AluisioASG @Anton-Latukha @aszlig @eadwu @jansol @JulienMalka @ckauhaus @marius851000 @Scriptkiddi @svanderburg @tobiasBora @l0b0
- Everybody who doesn't have an Email registered (part 1): @DontEatOreo @Enzime @Et7f3 @Garmelon

**Comment by infinisil** [comment]
Continuation of the above because of the 50 mentions per comment limit:
- Everybody who doesn't have an Email registered (part 2): @GeopJr @JesusMtnez @Kiskae @Kupac @Lord-Valen @MMesch @TomaSajt @Yarny0 @akirak @arcnmx @arthsmn @atemp @bb2020 @benradf @bratfizyk @chewblacka @cidkidnix @cpcloud @datafoo @donovanglover @ethanabrooks @fetsorn @freezeboy @hadilq @haenoe @henrik-ch @ivankovnatsky @jnetod @jpds @kacperwyczawski @katexochen @klemensn @lasers @marsam @mexisme @mfrischknecht @mkenigs @omasanori @orivej-nixos @polykernel @schnusch @seanybaggins @stuebinm @superwhiskers @tfmoraes @willcohen @xrelkd @xworld21 @ymatsiuk @zowoq

Please [set/update your Email](https://github.com/NixOS/SC-election-2024/blob/main/doc/email.md) to be able to vote.

**Comment by l0b0** [comment]
>     * Everybody whose Email failed to be sent: […] @l0b0

My address in the list is correct, and I'm able to receive emails on that address. What was the issue when sending? (Also, is there a better forum to discuss this?)

**Comment by infinisil** [comment]
Additional people whose Email failed to be sent: @tjni @avnik @lovek323 @luc65r @panicgh @oluceps @poscat0x04 @samuelgrf @pupbrained @foo-dogsquared

Please [check/update your email address](https://github.com/NixOS/SC-election-2024/blob/main/doc/email.md).
