### ISSUE TITLE
How will you help reduce the number of build failures?

### ISSUE THREAD

**Issue by myclevorname** [NixOS/SC-election-2024#86]
### Question

According to [Hydra](https://hydra.nixos.org/jobset/nixos/trunk-combined), there are around 2000 build failures in nixos-unstable, and the only time I know of where the community is wholly focused on reducing it is ZHF. What is your plan for reducing the number of build failures?

### Reminder of the Q&A rules

Please adhere to the [Q&A guidelines and rules](https://github.com/NixOS/SC-election-2024/blob/main/doc/qna.md)

**Comment by infinisil** [comment]
@myclevorname: As you are currently not an eligible voter, please abstain from the election processes. You may consider [requesting an exception](https://github.com/NixOS/SC-election-2024/blob/main/doc/exception-request.md).

**Comment by myclevorname** [comment]
@infinisil Unfortunately, I have contributed only 3 closed PR's to Nixpkgs, so I am unable to request an exception. Do I close this issue?

**Comment by infinisil** [comment]
@myclevorname Yeah let's close this to adhere to the process. If any voter is interesting in asking this question, they can do so by opening a new issue. And if a candidate would like to answer this, they can also do so and effectively answer their own question :)
